services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    environment:
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - AWS_DEFAULT_REGION=us-west-2
volumes:
  dynamodb_data:
